import Foundation
import SwiftUI
import Combine

class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()

    @Published var currentLanguage: String {
        didSet {
            UserDefaults.standard.set(currentLanguage, forKey: "app_language")
        }
    }

    init() {
        self.currentLanguage = UserDefaults.standard.string(forKey: "app_language") ?? "en"
    }

    func localizedString(_ key: String) -> String {
        let translations: [String: [String: String]] = [
            // Navigation & Common
            "select_community": ["en": "Select a Community", "zh": "选择社区"],
            "cancel": ["en": "Cancel", "zh": "取消"],
            "done": ["en": "Done", "zh": "完成"],
            "save": ["en": "Save", "zh": "保存"],
            "close": ["en": "Close", "zh": "关闭"],
            "error": ["en": "Error", "zh": "错误"],
            "add": ["en": "Add", "zh": "添加"],
            "edit": ["en": "Edit", "zh": "编辑"],
            "delete": ["en": "Delete", "zh": "删除"],

            // Login View
            "login": ["en": "Login", "zh": "登录"],
            "select_site": ["en": "Select Site", "zh": "选择站点"],
            "site": ["en": "Site", "zh": "站点"],
            "credentials": ["en": "Credentials", "zh": "凭证"],
            "username": ["en": "Username", "zh": "用户名"],
            "password": ["en": "Password", "zh": "密码"],
            "save_credentials": ["en": "Save Credentials", "zh": "保存凭证"],
            "credentials_saved": ["en": "Credentials saved successfully!", "zh": "凭证保存成功！"],
            "note": ["en": "Note", "zh": "注意"],
            "credentials_note": ["en": "Credentials are stored locally on your device. They will be used to access member-only content on the selected forum.", "zh": "凭证存储在您的设备上。它们将用于访问所选论坛的会员专属内容。"],

            // Settings View
            "settings": ["en": "Settings", "zh": "设置"],
            "gemini_api_key": ["en": "Gemini API Key", "zh": "Gemini API 密钥"],
            "enter_api_key": ["en": "Enter API Key", "zh": "输入 API 密钥"],
            "api_key_note": ["en": "Get your API key from Google AI Studio", "zh": "从 Google AI Studio 获取您的 API 密钥"],

            // AI Summary
            "ai_assistant": ["en": "AI Assistant", "zh": "AI 助手"],
            "gemini_analyzing": ["en": "Gemini is analyzing the content...", "zh": "Gemini 正在分析内容..."],
            "failed_summary": ["en": "Failed to generate summary.", "zh": "生成摘要失败。"],
            "check_api_key": ["en": "Please check your API Key in Settings.", "zh": "请在设置中检查您的 API 密钥。"],
            "try_again": ["en": "Try Again", "zh": "重试"],
            "gemini_summary": ["en": "Gemini Summary", "zh": "Gemini 摘要"],
            "cached": ["en": "Cached", "zh": "已缓存"],
            "generated_by": ["en": "Generated by Google Gemini", "zh": "由 Google Gemini 生成"],
            "regenerate": ["en": "Regenerate", "zh": "重新生成"],

            // Thread Detail & Reply
            "thread_reply": ["en": "Reply to thread...", "zh": "回复主题..."],
            "reply": ["en": "Reply", "zh": "答复"],
            "reply_failed": ["en": "Reply Failed", "zh": "回复失败"],
            "replying_to": ["en": "Replying to", "zh": "回复"],
            "said": ["en": "said", "zh": "说"],

            // New Thread View
            "new_thread": ["en": "New Thread", "zh": "发布新主题"],
            "post_failed": ["en": "Post Failed", "zh": "发布失败"],
            "thread_title": ["en": "Thread Title", "zh": "主题标题"],
            "share_thoughts": ["en": "Share your thoughts...", "zh": "分享您的想法..."],
            "attachments_header": ["en": "ATTACHMENTS", "zh": "附件"],
            "add_images": ["en": "Add Images", "zh": "添加图片"],
            "thread_button": ["en": "Post", "zh": "发布"],
            "word_count": ["en": "%d words", "zh": "%d 字"],

            // Bookmarks
            "bookmarks": ["en": "Bookmarks", "zh": "收藏"],
            "no_bookmarks": ["en": "No bookmarks yet", "zh": "暂无收藏"],

            // Community Config
            "communities": ["en": "Communities", "zh": "社区"],

            // RSS Feed Management
            "manage_feeds": ["en": "Manage Feeds", "zh": "管理订阅"],
            "no_rss_feeds": ["en": "No RSS Feeds", "zh": "暂无 RSS 订阅"],
            "add_feeds_description": ["en": "Add feeds manually or import from an OPML file", "zh": "手动添加订阅或从 OPML 文件导入"],
            "add_feed_manually": ["en": "Add Feed Manually", "zh": "手动添加订阅"],
            "import_from_opml": ["en": "Import from OPML", "zh": "从 OPML 导入"],
            "add_rss_feed": ["en": "Add RSS Feed", "zh": "添加 RSS 订阅"],
            "feed_name": ["en": "Feed Name", "zh": "订阅名称"],
            "feed_url": ["en": "Feed URL", "zh": "订阅地址"],
            "delete_count": ["en": "Delete (%d)", "zh": "删除 (%d)"],
            "already_added": ["en": "Already added", "zh": "已添加"],
            "new_feeds_count": ["en": "New Feeds (%d)", "zh": "新订阅 (%d)"],
            "already_subscribed_count": ["en": "Already Subscribed (%d)", "zh": "已订阅 (%d)"],
            "select_all": ["en": "Select All", "zh": "全选"],
            "deselect_all": ["en": "Deselect All", "zh": "取消全选"],
            "import_count": ["en": "Import (%d)", "zh": "导入 (%d)"],

            // Daily RSS Summary
            "daily_rss_summary": ["en": "Daily RSS Summary", "zh": "每日 RSS 摘要"],
            "daily_briefing": ["en": "Daily Briefing", "zh": "每日简报"],
            "last_24h": ["en": "Last 24h", "zh": "最近24小时"],
            "fetching_summary": ["en": "Fetching updates & generating summary...", "zh": "正在获取更新并生成摘要..."],
            "articles_found": ["en": "Found %d articles so far...", "zh": "已找到 %d 篇文章..."],
            "no_summary": ["en": "No summary available.", "zh": "暂无摘要。"],
            "generate_daily_summary": ["en": "Generate Daily Summary", "zh": "生成每日摘要"],
            "no_updates_24h": ["en": "No updates found in the last 24 hours.", "zh": "最近24小时内没有更新。"],

            // Image Viewer
            "failed_load_image": ["en": "Failed to load image", "zh": "图片加载失败"],
            "rotate_left": ["en": "Left", "zh": "左转"],
            "rotate_right": ["en": "Right", "zh": "右转"],

            // Login (extended)
            "login_with_browser": ["en": "Sign In via Browser", "zh": "通过浏览器登录"],
            "login_to_site": ["en": "Sign in to", "zh": "登录"],
            "login_captcha_support": ["en": "Supports captcha & 2FA verification", "zh": "支持验证码和双重验证"],
            "login_or": ["en": "or", "zh": "或"],
            "login_with_provider": ["en": "Quick Sign In", "zh": "快捷登录"],
            "login_success": ["en": "Login Successful!", "zh": "登录成功！"],
            "login_web_note": ["en": "You will be redirected to the website to sign in. Your session cookies are saved locally for future use.", "zh": "您将被重定向到网站进行登录。您的会话 Cookie 将保存在本地以供后续使用。"],
            "login_status": ["en": "Status", "zh": "状态"],
            "signed_in": ["en": "Signed in", "zh": "已登录"],
            "signed_out": ["en": "Not signed in", "zh": "未登录"],
            "logout": ["en": "Sign Out", "zh": "退出登录"],
            "save_session": ["en": "Save Session", "zh": "保存会话"],

            // In-App Browser & URL Bookmarks
            "browser": ["en": "Browser", "zh": "浏览器"],
            "thread_bookmarks": ["en": "Posts", "zh": "帖子"],
            "url_bookmarks": ["en": "Web Pages", "zh": "网页"],
        ]

        if let languageDict = translations[key],
           let translation = languageDict[currentLanguage] {
            return translation
        }
        return key // Fallback to key if translation not found
    }

    func localizedString(_ key: String, _ args: CVarArg...) -> String {
        let format = localizedString(key)
        return String(format: format, arguments: args)
    }
}

// Extension for convenience
extension String {
    func localized() -> String {
        return LocalizationManager.shared.localizedString(self)
    }

    func localized(_ args: CVarArg...) -> String {
        return LocalizationManager.shared.localizedString(self, args)
    }
}
